#output "cluster_id" {
#  description = "EKS cluster ID."
#  value       = try(module.eks.cluster_id, 0)
#}

#output "cluster_endpoint" {
#  description = "Endpoint for EKS control plane."
#  value       = try(module.eks.cluster_endpoint, 0)
#}

#output "cluster_security_group_id" {
#  description = "Security group ids attached to the cluster control plane."
#  value       = try(module.eks.cluster_security_group_id, 0)
#}

#output "kubectl_config" {
#  description = "kubectl config as generated by the module."
#  value       = try(module.eks.kubeconfig, 0)
#}

#output "config_map_aws_auth" {
#  description = "A kubernetes configuration to authenticate to this EKS cluster."
#  value       = try(module.eks.config_map_aws_auth, 0)
#}

output "region" {
  description = "AWS region"
  value       = var.aws_region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}
